import { test } from "node:test";
import assert from "node:assert/strict";
import { chromium, expect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { randomBytes, scryptSync } from "node:crypto";
import { existsSync, mkdirSync } from "node:fs";
test("Admin approval, expiry, revoked sessions, renewal and shop isolation", { timeout: 120000 }, async () => {
  const db = new PrismaClient();
  const browser = await chromium.launch({ headless: true, executablePath: ["C:/Program Files/Google/Chrome/Application/chrome.exe", "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"].find(existsSync) });
  const shopContext = await browser.newContext(); const page = await shopContext.newPage(); const adminPage = await browser.newPage();
  const email = `admin-test-shop-${Date.now()}@example.com`; const adminEmail = `admin-test-${Date.now()}@example.com`; const password = randomBytes(18).toString("hex");
  const salt = randomBytes(16).toString("hex"); let shop; let admin;
  try {
    admin = await db.admin.create({ data: { name: "Test Admin", email: adminEmail, passwordHash: `${salt}:${scryptSync(password, salt, 64).toString("hex")}` } });
    await page.goto("http://127.0.0.1:3000/login");
    await page.getByRole("button", { name: "Tạo shop mới", exact: true }).click();
    await page.getByLabel("Tên shop").fill("Shop thử quyền admin");
    await page.getByLabel("Email", { exact: true }).fill(email); await page.getByLabel("Mật khẩu", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Tạo shop", exact: true }).click();
    await expect(page.locator('p[role=alert]')).toContainText("chờ quản trị viên");
    shop = await db.shop.findUniqueOrThrow({ where: { email } }); assert.equal(shop.accessStatus, "pending");
    assert.equal(await db.session.count({ where: { shopId: shop.id } }), 0);
    await page.goto("http://127.0.0.1:3000/orders"); await expect(page).toHaveURL(/\/login/);
    await adminPage.goto("http://127.0.0.1:3000/admin/login");
    await adminPage.getByLabel("Email", { exact: true }).fill(adminEmail); await adminPage.getByLabel("Mật khẩu", { exact: true }).fill(password);
    await adminPage.getByRole("button", { name: "Đăng nhập quản trị", exact: true }).click();
    await expect(adminPage).toHaveURL("http://127.0.0.1:3000/admin");
    await adminPage.getByLabel("Tìm shop").fill(email); await adminPage.getByRole("button", { name: "Tìm kiếm", exact: true }).click();
    const card = adminPage.locator(".admin-shop");
    await card.getByLabel("Trạng thái", { exact: true }).selectOption("active");
    const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
    await card.getByLabel("Sử dụng đến hết ngày").fill(tomorrow);
    await card.getByRole("button", { name: "Lưu quyền sử dụng" }).click();
    await expect(card.getByRole("status")).toBeVisible();
    await expect(card.getByLabel("Trạng thái", { exact: true })).toHaveValue("active");
    assert.equal((await db.shop.findUniqueOrThrow({ where: { id: shop.id } })).accessStatus, "active");
    await page.getByLabel("Email", { exact: true }).fill(email); await page.getByLabel("Mật khẩu", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Vào shop của bạn" }).click(); await expect(page).toHaveURL("http://127.0.0.1:3000/");
    await page.goto("http://127.0.0.1:3000/admin"); await expect(page).toHaveURL(/\/admin\/login/);
    await page.goto("http://127.0.0.1:3000/products");
    const stale = await page.context().newPage();
    await stale.route('**/api/session', (route) => route.fulfill({ json: { active: true, accessUntil: null } }));
    await stale.goto("http://127.0.0.1:3000/products");
    await stale.getByRole("button", { name: "Thêm sản phẩm", exact: true }).click();
    await stale.getByLabel("Tên sản phẩm", { exact: true }).fill("Không được lưu sau hết hạn");
    await db.shop.update({ where: { id: shop.id }, data: { accessUntil: new Date(Date.now() + 2000) } });
    await page.reload();
    await expect(page).toHaveURL(/\/login\?reason=expired/, { timeout: 20000 });
    await expect(page.locator('p[role=alert]')).toContainText("Bạn cần gia hạn để được tiếp tục sử dụng");
    assert.equal(await db.session.count({ where: { shopId: shop.id } }), 0);
    await stale.getByRole("button", { name: "Lưu sản phẩm", exact: true }).click();
    await stale.waitForTimeout(500);
    assert.equal(await db.product.count({ where: { shopId: shop.id } }), 0);
    await stale.close();
    await page.getByLabel("Email", { exact: true }).fill(email); await page.getByLabel("Mật khẩu", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Vào shop của bạn" }).click();
    await expect(page.locator('p[role=alert]')).toContainText("Bạn cần gia hạn");
    assert.equal(await db.session.count({ where: { shopId: shop.id } }), 0);
    await adminPage.reload();
    await card.getByLabel("Sử dụng đến hết ngày").fill(tomorrow);
    await card.getByRole("button", { name: "Lưu quyền sử dụng" }).click(); await expect(card.getByRole("status")).toBeVisible();
    await page.getByLabel("Mật khẩu", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Vào shop của bạn" }).click(); await expect(page).toHaveURL("http://127.0.0.1:3000/");
    await card.getByLabel("Trạng thái", { exact: true }).selectOption("suspended");
    await card.getByRole("button", { name: "Lưu quyền sử dụng" }).click();
    await expect.poll(() => db.session.count({ where: { shopId: shop.id } })).toBe(0);
    await expect(card.getByRole("status")).toBeVisible();
    await expect(card.getByLabel("Trạng thái", { exact: true })).toHaveValue("suspended");
    await adminPage.reload();
    await expect(card.getByLabel("Trạng thái", { exact: true })).toHaveValue("suspended");
    await page.goto("http://127.0.0.1:3000/orders"); await expect(page).toHaveURL(/\/login/);
    assert.equal(await db.adminEvent.count({ where: { shopId: shop.id } }), 3);
    mkdirSync("artifacts", { recursive: true });
    for (const width of [1440, 390]) { await adminPage.setViewportSize({ width, height: 900 }); assert.ok(await adminPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); await adminPage.screenshot({ path: `artifacts/admin-${width}.png`, fullPage: true }); }
    const customer = await db.customer.create({ data: { shopId: shop.id, code: "KH000001", name: "Delete fixture", phone: "0900000000", address: "", identityKey: "delete-fixture" } });
    const product = await db.product.create({ data: { shopId: shop.id, name: "Delete fixture", price: 100 } });
    const order = await db.order.create({ data: { shopId: shop.id, code: "DH000001", customerId: customer.id, productId: product.id, product: product.name, customer: customer.name, phone: customer.phone, address: "", date: tomorrow, time: "09:00", price: 100 } });
    await db.orderItem.create({ data: { orderId: order.id, shopId: shop.id, productId: product.id, name: product.name, quantity: 1, unitPrice: 100, position: 0 } });
    await db.orderPayment.create({ data: { orderId: order.id, shopId: shop.id, amount: 100, method: "cash", position: 0 } });
    await card.getByRole("button", { name: "Xóa tài khoản shop", exact: true }).click();
    await expect(card.getByRole("button", { name: "Xóa vĩnh viễn", exact: true })).toBeDisabled();
    await card.getByLabel("Email xác nhận xóa").fill(email);
    await card.getByRole("button", { name: "Xóa vĩnh viễn", exact: true }).click();
    await expect(card).toHaveCount(0);
    assert.equal(await db.shop.count({ where: { id: shop.id } }), 0);
    for (const model of [db.order, db.orderItem, db.orderPayment, db.customer, db.product, db.adminEvent]) assert.equal(await model.count({ where: { shopId: shop.id } }), 0);
    assert.equal(await db.admin.count({ where: { id: admin.id } }), 1);
  } catch (error) { console.log(await adminPage.locator("main").innerText()); throw error; } finally {
    await db.shop.deleteMany({ where: { email } });
    if (admin) await db.admin.delete({ where: { id: admin.id } });
    await db.authAttempt.deleteMany({ where: { key: { in: [email, `admin:${adminEmail}`] } } });
    await browser.close(); await db.$disconnect();
  }
});
