import { approveFixture } from "./approve-fixture.mjs";
import { test } from "node:test";
import assert from "node:assert/strict";
import { chromium, expect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { existsSync, mkdirSync } from "node:fs";
import { navigate } from "./navigation.mjs";

test("Multiple order items: suggestions, direct entry, totals, edit, isolation and responsive composer", { timeout: 120000 }, async () => {
  const db = new PrismaClient();
  const email = `items-${Date.now()}@example.com`;
  const browser = await chromium.launch({ headless: true, executablePath: ["C:/Program Files/Google/Chrome/Application/chrome.exe", "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"].find(existsSync) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const base = "http://127.0.0.1:3000";
  const browserErrors = [];
  page.on("pageerror", (error) => browserErrors.push(error.message));
  let foreignShop;
  try {
    await page.goto(base);
    await page.getByRole("button", { name: "Tạo shop mới", exact: true }).click();
    await page.getByLabel("Tên shop").fill("Shop kiểm tra nhiều sản phẩm");
    await page.getByLabel("Email", { exact: true }).fill(email);
    await page.getByLabel("Mật khẩu").fill("ItemsTest123!");
    await page.getByRole("button", { name: "Tạo shop", exact: true }).click();
      await approveFixture(page, db);
    await page.getByRole("button", { name: "Tạo đơn hàng", exact: true }).waitFor();
    const shop = await db.shop.findUniqueOrThrow({ where: { email } });
    const product = await db.product.create({ data: { shopId: shop.id, name: "Hoa ly hồng pastel", price: 395000 } });
    foreignShop = await db.shop.create({ data: { email: `foreign-${email}`, name: "Foreign", passwordHash: "unused" } });
    const foreignProduct = await db.product.create({ data: { shopId: foreignShop.id, name: "Hoa ly riêng tư", price: 1 } });
    await page.reload();
    await page.getByRole("button", { name: "Tạo đơn hàng", exact: true }).click();
    await expect(page.getByLabel("Ngày đặt đơn", { exact: true })).toHaveCount(0);
    await expect(page.getByLabel("Giờ lên đơn", { exact: true })).toHaveCount(0);
    await expect.poll(() => page.locator(".order-items-scroll").evaluate((el) => el.clientHeight)).toBeGreaterThan(0);
    const initialProductHeight = await page.locator(".order-items-scroll").evaluate((el) => el.clientHeight);
    const input = page.getByRole("combobox", { name: "Sản phẩm", exact: true });
    await input.fill("Hoa mới thêm nhanh");
    await page.getByRole("button", { name: "Thêm sản phẩm nhanh", exact: true }).click();
    await expect.poll(async () => JSON.parse(await page.locator('input[name="items"]').inputValue())[0].productId).toBeTruthy();
    const quickProduct = await db.product.findFirstOrThrow({ where: { shopId: shop.id, name: "Hoa mới thêm nhanh" } });
    assert.equal(quickProduct.price, 0);
    assert.equal(JSON.parse(await page.locator('input[name="items"]').inputValue())[0].productId, quickProduct.id);
    assert.equal(await db.product.count({ where: { shopId: foreignShop.id, name: quickProduct.name } }), 0);
    assert.equal(await db.order.count({ where: { shopId: shop.id } }), 0);
    await input.fill("ly hong");
    await expect(page.getByRole("listbox", { name: "Sản phẩm gợi ý 1" }).getByRole("option")).toHaveCount(1);
    await input.press("ArrowDown"); await input.press("Enter");
    await expect(input).toHaveValue(product.name);
    await page.getByLabel("Số lượng", { exact: true }).fill("2");
    await page.getByRole("button", { name: "Thêm sản phẩm", exact: true }).click();
    await page.getByRole("combobox", { name: "Sản phẩm 2", exact: true }).fill("Bó hoa theo yêu cầu");
    await page.getByLabel("Đơn giá (₫)", { exact: true }).nth(1).fill("210000");
    await page.getByRole("combobox", { name: "Khách hàng", exact: true }).fill("Khách nhiều sản phẩm");
    await page.getByLabel("Số điện thoại", { exact: true }).fill("0901234567");
    await page.getByLabel("Địa chỉ").fill("12 Nguyễn Huệ");
    await page.getByLabel("Email khách hàng", { exact: true }).fill("customer@example.com");
    await page.getByLabel("Ngày sinh", { exact: true }).fill("1995-05-12");
    await page.getByLabel("Giới tính", { exact: true }).selectOption("female");
    await page.getByRole("button", { name: "Lưu thông tin khách hàng", exact: true }).click();
    await expect(page.locator(".customer-save [role=status]")).toContainText("Đã lưu thông tin khách hàng");
    const savedCustomer = await db.customer.findFirstOrThrow({ where: { shopId: shop.id, name: "Khách nhiều sản phẩm" } });
    assert.equal(savedCustomer.address, "12 Nguyễn Huệ");
    assert.equal(savedCustomer.email, "customer@example.com");
    assert.equal(savedCustomer.birthday, "1995-05-12");
    assert.equal(savedCustomer.gender, "female");
    assert.equal(await db.order.count({ where: { shopId: shop.id } }), 0);
    await expect(page.locator('input[name="customerId"]')).toHaveValue(savedCustomer.id);
    await expect(page.locator(".order-item-row")).toHaveCount(2);
    await page.getByLabel("Địa chỉ").fill("24 Nguyễn Huệ");
    await page.getByLabel("Email khách hàng", { exact: true }).fill("");
    await page.getByRole("button", { name: "Lưu thông tin khách hàng", exact: true }).click();
    await expect(page.getByRole("button", { name: "Lưu thông tin khách hàng", exact: true })).toBeEnabled();
    assert.equal((await db.customer.findUniqueOrThrow({ where: { id: savedCustomer.id } })).address, "24 Nguyễn Huệ");
    assert.equal(await db.customer.count({ where: { shopId: shop.id } }), 1);
    assert.equal((await db.customer.findUniqueOrThrow({ where: { id: savedCustomer.id } })).email, "");
    await expect.poll(() => page.locator(".order-items-scroll").evaluate((el) => el.clientHeight)).toBe(initialProductHeight);
    await page.getByLabel("Số tiền thanh toán 1", { exact: true }).fill("200000");
    await expect(page.getByLabel("Tổng tiền cần phải thu khách", { exact: true })).toHaveValue("1.000.000 ₫");
    await expect(page.getByLabel("Còn lại (₫)", { exact: true })).toHaveValue("800.000 ₫");
    mkdirSync("artifacts", { recursive: true });
    for (const width of [1440, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 1000 });
      if (width > 1000) await page.locator(".order-modal").evaluate((el) => el.scrollTop = 0);
      else await page.locator(".order-products").scrollIntoViewIfNeeded();
      assert.ok(await page.locator(".order-modal").evaluate((el) => el.scrollWidth <= el.clientWidth + 1), `dialog overflow at ${width}`);
      if (width === 1440) {
        const products = await page.locator(".order-products").boundingBox();
        const customer = await page.locator(".order-customer").boundingBox();
        assert.ok(products.x + products.width <= customer.x);
      }
      await page.screenshot({ path: `artifacts/order-multi-${width}.png`, fullPage: true });
      await page.locator(".compact-customer").screenshot({ path: `artifacts/customer-compact-${width}.png` });
    }
    for (let index = 0; index < 4; index++) await page.getByRole("button", { name: "Thêm sản phẩm", exact: true }).click();
    for (const width of [1440, 390]) {
      await page.setViewportSize({ width, height: 1000 });
      const list = page.locator(".order-items-scroll");
      await expect(list).toHaveClass(/is-scrollable/);
      await expect.poll(() => list.evaluate((el) => {
        const third = el.children[2], first = el.children[0];
        return Math.abs(el.clientHeight - (third.offsetTop + third.offsetHeight - first.offsetTop));
      })).toBeLessThanOrEqual(1);
      assert.ok(await list.evaluate((el) => el.scrollHeight > el.clientHeight));
      await list.evaluate((el) => el.scrollTop = el.scrollHeight);
      assert.ok(await list.evaluate((el) => el.scrollTop > 0));
      await list.screenshot({ path: `artifacts/order-products-scroll-${width}.png` });
    }
    for (let index = 6; index > 2; index--) await page.getByRole("button", { name: `Xóa sản phẩm ${index}`, exact: true }).click();
    await expect(page.locator(".order-items-scroll")).not.toHaveClass(/is-scrollable/);
    await expect(page.locator(".order-products")).not.toContainText("Thành tiền");
    await expect(page.locator(".order-products")).not.toContainText("Sản phẩm trực tiếp");
    await expect(page.locator(".order-modal .modal-head").getByRole("button", { name: "Lưu đơn hàng", exact: true })).toBeVisible();
    await expect(page.locator(".order-modal").getByRole("button", { name: "Đóng", exact: true })).toHaveCount(0);
    await page.getByLabel("Địa chỉ").fill("");
    await page.getByLabel("Ngày sinh", { exact: true }).fill("");
    await page.getByLabel("Giới tính", { exact: true }).selectOption("");
    await page.getByRole("button", { name: "Lưu đơn hàng", exact: true }).click();
    await page.locator(".order-modal").waitFor({ state: "detached" });
    let order = await db.order.findFirstOrThrow({ where: { shopId: shop.id }, include: { items: { orderBy: { position: "asc" } } } });
    assert.equal(order.price, 1000000); assert.equal(order.items.length, 2);
    assert.equal(order.address, "");
    let audit = await db.orderHistory.findMany({ where: { orderId: order.id } });
    assert.equal(audit.length, 1); assert.equal(audit[0].action, "created");
    assert.equal(audit[0].actorId, shop.id); assert.equal(audit[0].actorName, shop.name); assert.equal(audit[0].actorEmail, email);
    const placedDate = order.orderDate, placedTime = order.orderTime;
    assert.match(placedDate, /^\d{4}-\d{2}-\d{2}$/);
    assert.match(placedTime, /^\d{2}:\d{2}$/);
    assert.equal(order.items[0].quantity, 2); assert.equal(order.items[0].productId, product.id);
    assert.equal(order.items[1].productId, null);
    assert.equal(await db.product.count({ where: { shopId: shop.id } }), 2);
    await navigate(page, "Danh sách đơn");
    await expect(page.locator(".mobile-order")).toContainText("Bó hoa theo yêu cầu");
    await page.getByRole("button", { name: `Sửa đơn ${order.code}`, exact: true }).filter({ visible: true }).click();
    await expect(page.locator(".order-item-row")).toHaveCount(2);
    await page.getByLabel("Số lượng", { exact: true }).first().fill("3");
    await page.getByRole("button", { name: "Xóa sản phẩm 2", exact: true }).click();
    await expect(page.getByLabel("Tổng tiền cần phải thu khách", { exact: true })).toHaveValue("1.185.000 ₫");
    await page.getByRole("button", { name: "Thêm sản phẩm", exact: true }).click();
    await page.getByRole("combobox", { name: "Sản phẩm 2", exact: true }).fill("Hoa ly hồng pastel");
    await page.getByLabel("Đơn giá (₫)", { exact: true }).nth(1).fill("100000");
    // Exact catalog text remains a direct product until the user selects a suggestion.
    await page.locator('input[name="items"]').evaluate((el, foreignId) => {
      const items = JSON.parse(el.value); items[1].productId = foreignId; el.value = JSON.stringify(items);
    }, foreignProduct.id);
    await page.getByRole("button", { name: "Lưu đơn hàng", exact: true }).click();
    await expect(page.locator(".order-modal .error")).toContainText("Không tìm thấy sản phẩm");
    assert.equal((await db.order.findUniqueOrThrow({ where: { id: order.id } })).price, 1000000);
    assert.equal(await db.orderHistory.count({ where: { orderId: order.id } }), 1);
    await page.getByLabel("Đơn giá (₫)", { exact: true }).nth(1).fill("100001");
    await page.getByLabel("Đơn giá (₫)", { exact: true }).nth(1).fill("100000");
    await page.getByRole("button", { name: "Lưu đơn hàng", exact: true }).click();
    await page.locator(".order-modal").waitFor({ state: "detached" });
    order = await db.order.findUniqueOrThrow({ where: { id: order.id }, include: { items: { orderBy: { position: "asc" } } } });
    assert.equal(order.price, 1285000); assert.equal(order.items[1].productId, null);
    assert.equal(order.items[0].quantity, 3);
    assert.equal(await db.orderHistory.count({ where: { orderId: order.id } }), 2);
    assert.equal(order.orderDate, placedDate);
    assert.equal(order.orderTime, placedTime);
    await page.getByRole("link", { name: order.code, exact: true }).click();
    await expect(page).toHaveURL(`${base}/orders/${order.id}`);
    await expect(page.getByRole("heading", { name: `Đơn hàng ${order.code}`, exact: true })).toBeVisible();
    await expect(page.locator("dialog[open]")).toHaveCount(0);
    await page.getByRole("button", { name: "Thêm sản phẩm", exact: true }).click();
    await page.getByRole("combobox", { name: "Sản phẩm 3", exact: true }).fill("Thêm hoa tại trang chi tiết");
    await page.getByLabel("Đơn giá (₫)", { exact: true }).nth(2).fill("150000");
    await page.getByRole("button", { name: "Lưu đơn hàng", exact: true }).click();
    await expect(page.getByRole("status").filter({ hasText: "Đã lưu thay đổi đơn hàng" })).toBeVisible();
    const afterDetail = await db.order.findUniqueOrThrow({ where: { id: order.id }, include: { items: true } });
    assert.equal(afterDetail.items.length, 3);
    assert.equal(afterDetail.price, 1435000);
    assert.equal(afterDetail.orderDate, placedDate); assert.equal(afterDetail.orderTime, placedTime);
    assert.equal(await db.orderHistory.count({ where: { orderId: order.id } }), 3);
    await page.reload();
    await expect(page.locator(".order-item-row")).toHaveCount(3);
    await expect(page.getByRole("region", { name: "Lịch sử thay đổi đơn hàng" })).toContainText(shop.name);
    await page.getByRole("button", { name: "Lưu đơn hàng", exact: true }).click();
    await expect(page.getByRole("status").filter({ hasText: "Đã lưu thay đổi đơn hàng" })).toBeVisible();
    assert.equal(await db.orderHistory.count({ where: { orderId: order.id } }), 3);
    await page.getByLabel("Số tiền thanh toán 1", { exact: true }).fill("99999999");
    await page.getByRole("button", { name: "Lưu đơn hàng", exact: true }).click();
    await expect(page.locator(".order-form .error")).toBeVisible();
    assert.equal(await db.orderHistory.count({ where: { orderId: order.id } }), 3);
    await page.getByLabel("Số tiền thanh toán 1", { exact: true }).fill("450000");
    await page.locator(".order-form").evaluate((form) => { const input = document.createElement("input"); input.name = "actorName"; input.value = "Forged actor"; input.type = "hidden"; form.append(input); });
    await page.getByRole("button", { name: "Lưu đơn hàng", exact: true }).click();
    await expect(page.getByRole("status").filter({ hasText: "Đã lưu thay đổi đơn hàng" })).toBeVisible();
    audit = await db.orderHistory.findMany({ where: { orderId: order.id }, orderBy: { createdAt: "desc" } });
    assert.equal(audit.length, 4); assert.equal(audit[0].actorName, shop.name);
    assert.deepEqual(JSON.parse(audit[0].changes).find((change) => change.field === "Đã thanh toán"), { field: "Đã thanh toán", before: "200.000 ₫", after: "450.000 ₫" });
    await expect(page.locator(".history-entry").first()).toContainText("450.000 ₫");
    await page.getByLabel("Số tiền thanh toán 1", { exact: true }).fill("500000");
    await page.reload();
    assert.equal(await db.orderHistory.count({ where: { orderId: order.id } }), 4);
    await expect(page.getByLabel("Số tiền thanh toán 1", { exact: true })).toHaveValue("450.000");
    await page.getByLabel("Chi phí vận chuyển (₫)", { exact: true }).fill("50000");
    await page.getByLabel("Giảm giá (₫)", { exact: true }).fill("35000");
    await page.getByRole("button", { name: "Thêm lượt thanh toán", exact: true }).click();
    await page.getByLabel("Số tiền thanh toán 2", { exact: true }).fill("100000");
    await page.getByLabel("Phương thức thanh toán 2", { exact: true }).selectOption("transfer");
    await expect(page.getByLabel("Tổng tiền cần phải thu khách", { exact: true })).toHaveValue("1.450.000 ₫");
    await expect(page.getByLabel("Đã thanh toán (₫)", { exact: true })).toHaveValue("550.000 ₫");
    await expect(page.getByLabel("Còn lại (₫)", { exact: true })).toHaveValue("900.000 ₫");
    await page.getByRole("button", { name: "Lưu đơn hàng", exact: true }).click();
    await expect(page.getByRole("status").filter({ hasText: "Đã lưu thay đổi đơn hàng" })).toBeVisible();
    const multiplePayments = await db.order.findUniqueOrThrow({ where: { id: order.id }, include: { payments: { orderBy: { position: "asc" } } } });
    assert.equal(multiplePayments.shippingFee, 50000);
    assert.equal(multiplePayments.price, 1450000);
    assert.equal(multiplePayments.discount, 35000);
    assert.equal(multiplePayments.paidAmount, 550000);
    assert.deepEqual(multiplePayments.payments.map(({ amount, method }) => ({ amount, method })), [{ amount: 450000, method: "cash" }, { amount: 100000, method: "transfer" }]);
    await expect(page.locator(".history-entry").first()).toContainText("Chi phí vận chuyển");
    await expect(page.locator(".history-entry").first()).toContainText("Chuyển khoản");
    await page.reload();
    await expect(page.getByLabel("Phương thức thanh toán 2", { exact: true })).toHaveValue("transfer");
    await expect(page.getByLabel("Giảm giá (₫)", { exact: true })).toHaveValue("35.000");
    await expect(page.getByLabel("Tổng tiền cần phải thu khách", { exact: true })).toHaveValue("1.450.000 ₫");
    await expect(page.getByLabel("Chi phí vận chuyển (₫)", { exact: true })).toHaveValue("50.000");
    for (const width of [1440, 390, 320]) {
      await page.setViewportSize({ width, height: 1000 });
      const valueBox = await page.locator('.payment-value').boundingBox();
      const paymentBox = await page.locator('.payment-installments').boundingBox();
      if (width === 1440) { assert.ok(Math.abs(valueBox.y - paymentBox.y) < 1); assert.ok(paymentBox.x >= valueBox.x + valueBox.width); }
      else assert.ok(paymentBox.y >= valueBox.y + valueBox.height);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.evaluate(() => window.scrollTo(0, 0));
      await page.screenshot({ path: `artifacts/order-detail-${width}.png`, fullPage: true });
    }
    await page.getByRole("button", { name: "Quay lại", exact: true }).click();
    await expect(page).toHaveURL(`${base}/orders`);
    await page.locator(".mobile-order-product").click();
    await expect(page).toHaveURL(`${base}/orders/${order.id}`);
    await page.goto(`${base}/orders`);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator(".orders-table tbody tr td").first().click();
    await expect(page).toHaveURL(`${base}/orders/${order.id}`);
    const otherCustomer = await db.customer.create({ data: { shopId: foreignShop.id, code: "KH000001", name: "Private", phone: "0900000000", address: "", identityKey: "Private|0900000000" } });
    const otherOrder = await db.order.create({ data: { shopId: foreignShop.id, code: "DH000001", customerId: otherCustomer.id, customer: "Private", phone: "0900000000", address: "", product: "Secret foreign order", date: placedDate, orderDate: placedDate, time: "09:00", price: 1 } });
    const foreignResponse = await page.goto(`${base}/orders/${otherOrder.id}`);
    assert.equal(foreignResponse.status(), 404);
    await expect(page.getByText("Secret foreign order", { exact: true })).toHaveCount(0);
    assert.deepEqual(browserErrors, []);
  } finally {
    await db.shop.deleteMany({ where: { email: { in: [email, `foreign-${email}`] } } });
    await db.authAttempt.deleteMany({ where: { key: email } });
    await browser.close(); await db.$disconnect();
  }
});
