ALTER TABLE "Customer" ADD COLUMN "email" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Customer" ADD COLUMN "birthday" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Customer" ADD COLUMN "gender" TEXT NOT NULL DEFAULT '';
